name: Build d2lootfilter DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSVC
        uses: actions/setup-msbuild@v1

      - name: Build DLL
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 /p:OutputPath=./build
          copy ./build/*.dll ./d2lootfilter.dll
