name: Build Branch

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@master
    - name: MSBuild
      run: msbuild /t:d2lootfilter:Rebuild /p:Configuration=Release /property:Platform=x86 d2lootfilter.sln
    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Development Build"
        files: |
          Release/d2lootfilter.dll
          doc/ENG/item.filter